site_name: Deadlock Challenges Docs
nav:
  - Home: index.md
  - Types of challenge:
    - Code: challenge-types/code.md
    - SQL: challenge-types/sql.md
    - Multi service: challenge-types/multi-service.md
  - Mode: mode/index.md
  - How does it work ?: how-does-it-work.md
  - About: about.md
theme: readthedocs


